### ISSUE TITLE
TypeError: Tensors in list passed to 'values' of 'ConcatV2' Op have types [bool, float32] that don't all match.

### ISSUE THREAD

**Issue by DennisShaw** [huanghao128/zh-nlp-demo#1]
If the Keras or the Keras-Cotrib Version is wrong?Thanks

**Comment by huanghao128** [comment]
应该是keras版本问题，是不是类似这个：https://github.com/keras-team/keras-contrib/issues/515
我的版本：tensorflow=1.12.0, keras=2.2.4, keras-contrib=2.0.8

**Comment by huanghao128** [comment]
> If the Keras or the Keras-Cotrib Version is wrong?Thanks

应该是keras版本问题，是不是类似这个：keras-team/keras-contrib#515
我的版本：tensorflow=1.12.0, keras=2.2.4, keras-contrib=2.0.8
